networks:
  etl_network:

services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2022-11-08T05-27-07Z
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - etl_network
    volumes:
      - minio_data:/data   

  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5432:5432"
    restart: always
    networks:
      - etl_network

  redis:  
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - etl_network

  airflow:
    image: apache/airflow:2.10.5
    container_name: airflow
    depends_on:
      - postgres
      - redis
      - minio
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    ports:
      - "8082:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    command: webserver
    restart: always
    networks:
      - etl_network

  pyspark:
    build: .
    container_name: pyspark
    environment:
      - SPARK_JARS_PACKAGES=org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262,com.crealytics:spark-excel_2.12:3.3.2
    ports:
      - "8888:8888"
      - "4042:4041"
    networks:
      - etl_network
    depends_on:
      - minio
      - airflow
    volumes:
      - ./data:/data
      - ./notebooks:/home/jovyan/work

  nifi:
    image: apache/nifi:1.18.0
    container_name: nifi
    environment:
      NIFI_WEB_HTTP_PORT: "8081"
    ports:
      - "8081:8081"
    networks:
      - etl_network
    depends_on:
      - minio

  mariadb:
    container_name: mariadb
    image: mariadb:10.6
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    restart: always
    networks:
      - etl_network

  hive-metastore:
    container_name: hive_metastore
    image: ofrir119/hive-metastore:1.0
    ports:
      - "9083:9083"
    depends_on:
      - mariadb
    restart: always
    networks:
      - etl_network

  minio-client:
    image: minio/mc
    container_name: minio-client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 admin admin123;
      mc mb myminio/mybucket || true;
      tail -f /dev/null"
    networks:
      - etl_network

  logstash:
    image: logstash:7.13.2
    container_name: logstash
    restart: always
    networks:
      - etl_network

volumes:
  minio_data:
  postgres_data:
  airflow_logs:
  airflow_dags: